---
title: "factors_associated_with_changes_in_flight_traffic"
author: "Yuqi Tu, Jiaqi Li, Xin Yin"
date: "November 22, 2017"
output: html_document
---

```{r library, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidytext)
library(rvest)
library(httr)
library(haven)
library(janitor)
library(ggthemes)
library(ggplot2)
library(rnoaa)
library(stringr)
library(forcats)
library(viridis)
library(data.table)
library(stringr)
```

```{r combine datasets, message = FALSE, warning = FALSE}
system.time(fread("./Data/2016_01.csv"))

datasets = as.list(list.files("./Data"))
data_list_2016 = character()
for (i in 1:12) {
  output[[i]] = paste("./Data/", datasets[[i]], sep = "")
  data_list_2016 = c(data_list_2016, output[[i]])
}

load_data = function(path){
  files = dir(path, pattern = "\\.csv", full.names = TRUE)
  tables = lapply(files, fread)
  do.call(rbind, tables)
}

original_data = load_data("./Data")



```
```

finally <- c(finally, datasets[1])

temp = list.files(pattern =".Data/*.csv")

for (i in 1:length(datasets)) {
  assign(datasets[i], fread(datasets[i]))
}

lapply(data_list_2016, function)

```

